export const GENRES = [
  'Politics',
  'Business',
  'Technology',
  'Science',
  'Sports',
  'Entertainment',
  'Crime',
  'Health',
  'World',
  'Environment',
  'Weather',
  'Automotive',
  'Travel',
  'Food',
  'Education',
  'Real Estate',
  'Space',
  'AI & Robotics',
  'Gaming',
  'Fashion',
  'Crypto',
  'Military',
];

export const GENRE_COLORS = {
  Politics:        '#E63946',
  Business:        '#2DC653',
  Technology:      '#4CC9F0',
  Science:         '#B5179E',
  Sports:          '#F77F00',
  Entertainment:   '#FFBE0B',
  Crime:           '#FF6B35',
  Health:          '#06D6A0',
  World:           '#7209B7',
  Environment:     '#80ED99',
  Weather:         '#90E0EF',
  Automotive:      '#D4A373',
  Travel:          '#48BFE3',
  Food:            '#FF9F1C',
  Education:       '#7EC8E3',
  'Real Estate':   '#C9ADA7',
  Space:           '#9B5DE5',
  'AI & Robotics': '#00F5D4',
  Gaming:          '#F15BB5',
  Fashion:         '#FEC89A',
  Crypto:          '#F9C74F',
  Military:        '#6C757D',
};

export function getGenreColor(genre) {
  return GENRE_COLORS[genre] || '#AAAAAA';
}
